# Generated by Django 4.0.3 on 2022-04-11 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=15)),
                ('Last_name', models.CharField(max_length=15)),
                ('Date_of_birth', models.DateField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Membership_deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reserved_date', models.DateField()),
                ('Reserved_time_start', models.TimeField()),
                ('Reserved_time_end', models.TimeField()),
                ('Facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CC.facilities')),
                ('Member', models.ManyToManyField(to='CC.member')),
            ],
        ),
        migrations.CreateModel(
            name='Membership_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30)),
                ('Duration', models.DurationField()),
                ('Facilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CC.facilities')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='Membership_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CC.membership_type'),
        ),
    ]
