# Generated by Django 4.0.3 on 2022-04-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Court_number',
            field=models.IntegerField(default=0),
        ),
    ]
