# Generated by Django 4.0.3 on 2022-04-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0003_remove_member_email_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Membership_type',
        ),
        migrations.AddField(
            model_name='member',
            name='Membership_type',
            field=models.ManyToManyField(to='CC.membership_type'),
        ),
    ]
