# Generated by Django 4.0.3 on 2022-04-28 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0004_remove_member_membership_type_member_membership_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Membership_type',
        ),
        migrations.AddField(
            model_name='member',
            name='Membership_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CC.membership_type'),
        ),
    ]
